-- MySQL Script generated by MySQL Workbench
-- 03/30/16 19:36:12
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `system` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`Role` (
  `roleid` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`User` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `roleid` INT NOT NULL,
  PRIMARY KEY (`userid`),
  INDEX `fk_User_Role1_idx` (`roleid` ASC),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`roleid`)
    REFERENCES `system`.`Role` (`roleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`Room` (
  `roomid` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(45) NOT NULL,
  `room_master` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `limit` VARCHAR(45) NOT NULL,
  `lock` VARCHAR(45) NOT NULL,
  `create_at` VARCHAR(45) NOT NULL,
  `end_at` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`roomid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`User_has_Room` (
  `userid` INT NOT NULL,
  `roomid` INT NOT NULL,
  INDEX `fk_User_has_Room_User_idx` (`userid` ASC),
  INDEX `fk_User_has_Room_Room1_idx` (`roomid` ASC),
  CONSTRAINT `fk_User_has_Room_User`
    FOREIGN KEY (`userid`)
    REFERENCES `system`.`User` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Room_Room1`
    FOREIGN KEY (`roomid`)
    REFERENCES `system`.`Room` (`roomid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`Storage` (
  `storageid` INT NOT NULL AUTO_INCREMENT,
  `directory` VARCHAR(45) NOT NULL,
  `create_at` VARCHAR(45) NOT NULL,
  `roomname` VARCHAR(45) NOT NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`storageid`),
  INDEX `fk_Storage_User1_idx` (`userid` ASC),
  CONSTRAINT `fk_Storage_User1`
    FOREIGN KEY (`userid`)
    REFERENCES `system`.`User` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Storage_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`Storage_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `videoname` VARCHAR(45) NOT NULL,
  `storageid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Storage_details_Storage1_idx` (`storageid` ASC),
  CONSTRAINT `fk_Storage_details_Storage1`
    FOREIGN KEY (`storageid`)
    REFERENCES `system`.`Storage` (`storageid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
